### ISSUE TITLE
Problem in bookRide function and Expo / React Native

### ISSUE THREAD

**Issue by AndresEstacio89** [anchetaWern/grabClone#2]
Hi, I need a little help. I have a project in React Native for an app that works very similar to Uber (as in your grabClone project) but I'm doing it with "Expo" and as you know, Expo does not create the IOS and ANDROID folders. For this reason I am having problems to use the "bookRide" function because there you use RNGooglePlaces and React-Native-Google-Places-Picker is not compatible with Expo, because I can not configure the dependencies in Android. Maybe you could tell me which component I can replace React-Native-Google-Places-Picker ?? so that the bookRide function works in the same way?

**Comment by anchetaWern** [comment]
@AndresEstacio89  I'm afraid there are currently no alternative to those two modules. They're both native modules so you can't really install them on an Expo project. The only way I can think of is detaching your project to Expokit so you can still use Expo's APIs while being able to install native modules as well.

**Comment by AndresEstacio89** [comment]
Thank you for your answer!
